DROP TABLE EVENT_STORE_ENTRY;

CREATE TABLE EVENT_STORE_ENTRY (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	PARTITION_ID VARCHAR(1024) NOT NULL,
	BUCKET_ID VARCHAR(1024) NOT NULL,
	STREAM_ID UNIQUEIDENTIFIER NOT NULL,
	CHANGE_SET_ID UNIQUEIDENTIFIER NOT NULL,
	EVENT_CREATED DATETIME DEFAULT GETUTCDATE() NOT NULL,
	EVENT_CLASS_NAME VARCHAR(1024) NOT NULL,
	EVENT_VERSION BIGINT NOT NULL,
	EVENT VARCHAR(max) NOT NULL
);

CREATE UNIQUE INDEX UK_EVENT_ST_PI_BI_SI_EV ON EVENT_STORE_ENTRY(PARTITION_ID, BUCKET_ID, STREAM_ID, EVENT_VERSION);

CREATE INDEX K_EVENT_ST_PI_BI_SI_ECN_EV ON EVENT_STORE_ENTRY(PARTITION_ID, BUCKET_ID, STREAM_ID, EVENT_CLASS_NAME, EVENT_VERSION);

CREATE INDEX K_EVENT_ST_PI_BI_SI_CSI_EV ON EVENT_STORE_ENTRY(PARTITION_ID, BUCKET_ID, STREAM_ID, CHANGE_SET_ID, EVENT_VERSION);

CREATE INDEX K_EVENT_ST_PI_BI_SI_CSI_ECN_EV ON EVENT_STORE_ENTRY(PARTITION_ID, BUCKET_ID, STREAM_ID, CHANGE_SET_ID, EVENT_CLASS_NAME, EVENT_VERSION);
