DROP TABLE ACCOUNT_VIEW;
DROP TABLE TRANSACTION_VIEW;

CREATE TABLE ACCOUNT_VIEW (
	AGGREGATE_ID UNIQUEIDENTIFIER PRIMARY KEY,
	BALANCE DECIMAL(8,2) NOT NULL
);

CREATE TABLE TRANSACTION_VIEW (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	AGGREGATE_ID UNIQUEIDENTIFIER NOT NULL,
	TRANSACTION_CREATED DATETIME NOT NULL,
	TRANSACTION_TYPE CHARACTER(1) NOT NULL,
	BALANCE DECIMAL(8,2) NOT NULL
);
